# 
FROM python:3.9

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app /code/app

#
EXPOSE 8000

#This will not be executed as we are using docker-compose
#Add true or false argument for reload state. By default its false
CMD ["python", "-m","app.main"] 