import { ClientOnly, IconButton, Skeleton, Span } from '@chakra-ui/react';
import { useColorMode as useChakraColorMode } from '@chakra-ui/react';

import * as React from 'react'
import { LuMoon, LuSun } from 'react-icons/lu'

// This file was auto-generated by chakra UI's v3 migration tool
// we can customize the color mode hooks here if we want to add additional functionality.

// This is where we implement light/dark mode support for the app, and the toggle 
// button that allows users to switch between modes

export function useColorMode() {
  const { colorMode, setColorMode, toggleColorMode } = useChakraColorMode()
  return {
    colorMode,
    setColorMode,
    toggleColorMode,
  }
}

export function useColorModeValue(light, dark) {
  const { colorMode } = useColorMode()
  return colorMode === 'dark' ? dark : light
}

export function ColorModeIcon() {
  const { colorMode } = useColorMode()
  return colorMode === 'dark' ? <LuMoon /> : <LuSun />
}

export const ColorModeButton = React.forwardRef(
  function ColorModeButton(props, ref) {
    const { toggleColorMode } = useColorMode()
    return (
      <ClientOnly fallback={<Skeleton boxSize='9' />}>
        <IconButton
          onClick={toggleColorMode}
          variant='ghost'
          aria-label='Toggle color mode'
          size='sm'
          ref={ref}
          {...props}
          css={{
            _icon: {
              width: '5',
              height: '5',
            },
          }}
        >
          <ColorModeIcon />
        </IconButton>
      </ClientOnly>
    )
  },
)

export const LightMode = React.forwardRef(function LightMode(props, ref) {
  return (
    <Span
      color='fg'
      display='contents'
      className='chakra-theme light'
      colorPalette='gray'
      ref={ref}
      {...props}
    />
  );
})

export const DarkMode = React.forwardRef(function DarkMode(props, ref) {
  return (
    <Span
      color='fg'
      display='contents'
      className='chakra-theme dark'
      colorPalette='gray'
      ref={ref}
      {...props}
    />
  );
})
