import { ChakraProvider, defaultSystem } from '@chakra-ui/react';

// this file was also auto-generated by chakra UI's v3 migration tool

export function Provider(props) {
  return (
    <ChakraProvider value={defaultSystem}>
      {props.children}
    </ChakraProvider>
  );
}
