import { ChakraProvider } from '@chakra-ui/react';
import { system } from '../../theme';

// this file was also auto-generated by chakra UI's v3 migration tool

export function Provider(props) {
  return (
    <ChakraProvider value={system}>
      {props.children}
    </ChakraProvider>
  );
}
